homeassistant:
  name: !secret name
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: !secret elevation_home
  unit_system: metric
  time_zone: Europe/Oslo
  customize: !include customize.yaml
  packages: !include_dir_named packages/

frontend:
  themes: !include themes.yaml

http:
  # api_password: !secret http_password
  base_url: !secret base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

# asuswrt:
#   host: !secret asus_ip
#   username: !secret asus_user
#   password: !secret asus_pass
#   port: 23
#   protocol: telnet

circadian_lighting:
  sunrise_time: '06:00:00'
  sunset_time: '19:30:00'
  transition: 3600
  max_colortemp: 4500
  min_colortemp: 2203
  interval: 300


config:

conversation:

device_tracker:
  # - platform: asuswrt
    # host: !secret asus_ip
    # username: !secret asus_user
    # password: !secret asus_pass
    # protocol: telnet
    # interval_seconds: 12
    # track_new_devices: false
    # consider_home: 180

discovery:

# googlehome:
#   devices:
#     - host: 10.0.10.1

history:

hue:
  bridges:
    - host: !secret hue_ip

###INCLUDES###
automation: !include_dir_merge_list automations/
binary_sensor: !include components/binary_sensor.yaml
camera: !include components/cameras.yaml
climate: !include components/climate.yaml
group: !include groups.yaml
input_boolean: !include components/input_boolean.yaml
input_number: !include components/input_number.yaml
ios: !include components/ios.yaml
light: !include components/lights.yaml
media_player: !include components/media_player.yaml
plant: !include plants.yaml
script: !include_dir_merge_named scripts/
sensor: !include_dir_merge_list sensors/
switch: !include components/switch.yaml
zone: !include components/zones.yaml

ifttt:
  key: !secret ifttt_key

#influxdb:
#  host: !secret influxd_ip

logbook:

logger:
  default: info

map:

mobile_app:

recorder:
  purge_keep_days: 5
#   purge_interval: 1

# rfxtrx:
#   device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A12IY0JX-if00-port0
shopping_list:

skybell:
  username: !secret skybell_user
  password: !secret skybell_pass

sun:

# system_health:

tibber:
  access_token: !secret tibber_token

tts:
  platform: google_translate

tradfri:
  host: !secret tradfri_ip
  allow_tradfri_groups: false

updater:

vacuum:
  - platform: roomba
    host: !secret stovemaskin_ip
    name: "Støvemaskin"
    username: !secret stovemaskin_user
    password: !secret stovemaskin_pass

volkswagencarnet:
    username: !secret carnet_user
    password: !secret carnet_pass
    scan_interval:
      minutes: 5
    name:
      wvwzzzauzfw902401: 'I&Ts eGolf'

weather:
  - platform: met

zwave:
     usb_path: /dev/ttyACM0
     network_key: !secret zwave_key
