  # - platform: template
  #   sensors:
  #     idlock_battery:
  #       value_template: >-
  #         {%- if states.zwave.front_door_lock_101 -%}
  #           {{ states.zwave.front_door_lock_101.attributes.battery_level }}
  #         {%- else -%}
  #           n/a
  #         {%- endif -%}
  #       unit_of_measurement: '%'
  #       entity_id: zwave.front_door_lock_101
  #       friendly_name: "Battery IDLock"

- platform: template
  sensors:
    idlock_battery:
      value_template: '{{ states.zwave.front_door_lock_101.attributes.battery_level }}'
      friendly_name: 'Battery IDLock'
      entity_id: zwave.front_door_lock_101
      unit_of_measurement: '%'
      icon_template: >-
        {% set battery_level = states('sensor.idlock_battery')|int('unknown') %}
        {% set battery_round = (battery_level|int / 10)|int * 10 %}
        {% if battery_level == 'unknown' %}
          mdi:battery-unknown
        {% else %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
        {% endif %}
